# .github/workflows/build.yml

# The name of your automated workflow.
name: Build VortexChestShop Plugin

# Triggers the workflow on push or pull request events for the main branch.
on:
  push:
    branches: [ "main" ] # Trigger on pushes to the 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests targeting the 'main' branch

jobs:
  build:
    # The type of virtual machine to use for building the plugin.
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment for each build

    steps:
      # Step 1: Checks out your repository code so the workflow can access it.
      - name: Checkout Repository
        uses: actions/checkout@v4 # Uses the actions/checkout action to get your code

      # Step 2: Sets up the Java environment (JDK 17, as specified in your build.gradle).
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Uses the actions/setup-java action
        with:
          java-version: '17' # Specify Java 17, matching your build.gradle
          distribution: 'temurin' # Recommended distribution for robustness

      # Step 3: Set up the Gradle program on the virtual machine.
      # This action installs Gradle for us and sets up caching.
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3 # Uses the official Gradle setup action

      # Step 4: Run the build using the 'gradle' command directly.
      # The 'build' task will automatically run 'shadowJar' because you configured
      # 'shadowJar' as a dependency of 'jar' in your build.gradle, and 'jar' is
      # part of the default 'build' lifecycle.
      - name: Build with Gradle
        run: gradle build # Executes the Gradle build command

      # Step 5: Upload the compiled JAR file as a downloadable build artifact.
      # This makes the compiled plugin accessible from the GitHub Actions summary page.
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4 # Uses the actions/upload-artifact action
        with:
          # The name of the downloadable file in the GitHub Actions summary.
          name: VortexChestShop-Plugin # Renamed to match your plugin name
          # The path to the compiled JAR file. The wildcard '*' matches the version number
          # (e.g., VortexChestShop-1.0.0-SNAPSHOT.jar).
          path: build/libs/VortexChestShop-*.jar # Updated path to your plugin's JAR
          
